# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-21 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('week', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('record', models.CharField(default=b'-', max_length=20)),
                ('summary', models.TextField()),
            ],
            options={
                'ordering': ['year', 'week', 'rank'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=50)),
                ('conference', models.CharField(max_length=100)),
                ('division', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='ranking',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nbapowerranks.Team'),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nbapowerranks.Team'),
        ),
    ]
